Replacing custom nvim with LazyVim; standardizing setup script; adding is-installed script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -7,160 +7,162 @@
 # scoping the shellcheck directive to only this function.
 #
 # If /etc/os-release does not exist, assumes macos
-getOsType() {
+
+get_os_type() {
   # This is only applicable on Linux machines.
   if [[ -f /etc/os-release ]]; then
     # shellcheck disable=SC1091
     source /etc/os-release
 
-    echo "${ID_LIKE}"
+    local os_type="${ID_LIKE}"
+
+    if [[ -z "${os_type}" ]]; then
+      os_type="${ID}"
+    fi
+
+    echo "${os_type}"
   else
     echo "macos"
   fi
 }
-OS_TYPE=$(getOsType)
 
-# Grabbing the script's directory
-SCRIPT_PATH="$(realpath "${BASH_SOURCE[0]}")"
-SCRIPT_DIR="$(dirname "${SCRIPT_PATH}")"
+create_symlink() {
+  local origin_path="$1"
+  local target_path="$2"
 
-# Shorthand function for checking if software is installed
-isInstalled() {
-  command -v "${1}" &>/dev/null
-}
-
-symLink() {
-  local originPath="$1"
-  local targetPath="$2"
-
-  if [[ -f "${originPath}" ]]; then
-    # Need to make sure there's a valid target to symlink
-    [[ ! -f "${targetPath}" ]] && touch "${targetPath}"
-
-    ln -sf "${originPath}" "${targetPath}"
+  if [[ ! -e "${origin_path}" ]]; then
+    echo "create_symlink: Invalid origin path: ${origin_path}" >&2
   else
-    echo "symLink: Invalid origin path: ${originPath}"
+
+    if [[ -e "${target_path}" && ! -L "${target_path}" ]]; then
+      mv "${target_path}" "${target_path}.bak"
+    fi
+
+    ln -sf "${origin_path}" "${target_path}"
   fi
 }
 
 # Takes in origin directory and a target directory.
-# Iterates through all files within origin directory and creates symLinks within the target directory.
-symLinkDir() {
-  local originDir="${1}"
-  local targetDir="${2}"
+# Iterates through all files within origin directory and creates symLinks
+# within the target directory.
+symlink_dir_files() {
+  local origin_dir="${1}"
+  local target_dir="${2}"
 
-  if [[ -d "${originDir}" ]]; then
-    echo "Creating symLinks for ${originDir##*/} files.."
+  if [[ -d "${origin_dir}" ]]; then
+    echo "Creating symLinks for ${origin_dir##*/} files.."
 
     # Making sure targetDir exists
-    [[ ! -d "${targetDir}" ]] && mkdir -p "${targetDir}"
+    [[ ! -d "${target_dir}" ]] && mkdir -p "${target_dir}"
 
-    for file in "${originDir}"/*; do
-      local fileName="${file##*/}"
-      symLink "${file}" "${targetDir}/${fileName}"
+    for file in "${origin_dir}"/*; do
+      local file_name="${file##*/}"
+      create_symlink "${file}" "${target_dir}/${file_name}"
     done
 
     echo "Done." && echo ""
   else
-    echo "symLinkDir: ERROR: Invalid originDir: ${originDir}"
+    echo "symlink_dir_files: ERROR: Invalid originDir: ${origin_dir}" >&2
   fi
 }
 
-# i3 Configs
-if isInstalled i3; then
-  echo "Creating symLinks for i3.."
-  symLinkDir "${SCRIPT_DIR}/i3-wm" ~/.config/i3
-fi
-
-# picom Configs
-if isInstalled picom; then
-  echo "Creating symLinks for picom.."
-  symLink "${SCRIPT_DIR}/picom/picom.conf" ~/.config/picom.conf
-  echo "Done." && echo ""
-fi
-
-# Starship Configs
-if isInstalled starship; then
-  echo "Creating symLinks for starship.."
-  symLink "${SCRIPT_DIR}/starship/starship.toml" ~/.config/starship.toml
-  echo "NOTE: Starship requires adding \`eval \"\$(starship init bash)\"\` to your ~/.bashrc file"
-  echo "Done." && echo ""
-fi
-
-# Tmux Configs
-if isInstalled tmux; then
-  echo "Creating symLinks for tmux.."
-  symLink "${SCRIPT_DIR}/tmux/tmux.conf" ~/.tmux.conf
-  echo "Done." && echo ""
-fi
-
-# Alacritty Configs
-if isInstalled alacritty; then
-  echo "Creating symLinks for alacritty.."
-  [[ ! -d ~/.config/alacritty ]] && mkdir -p ~/.config/alacritty
-  symLink "${SCRIPT_DIR}/alacritty/alacritty.toml" ~/.config/alacritty/alacritty.toml
-  echo "Done." && echo ""
-fi
-
-# EDITOR to vim
-if [[ "${EDITOR}" != "vim" ]]; then
-  echo "Checking for EDITOR set to 'vim'.."
-  echo "NOTE: Your current EDITOR is not set to vim."
-  echo "Consider adding \`export EDITOR=vim\` to your ~/.bashrc"
-  echo "Done." && echo ""
-fi
-
-# Vimrc Configs
-if isInstalled vim; then
-  echo "Creating symLinks for vimrc.."
-  symLink "${SCRIPT_DIR}/vimrc/${OS_TYPE}-vimrc" ~/.vimrc
-  echo "Done." && echo ""
-fi
-
-# NeoVim Configs
-if isInstalled nvim; then
-  echo "Creating symLinks for nvim.."
-
-  HOME_NVIM="${HOME}/.config/nvim"
-  HOME_PLUGINS="${HOME_NVIM}/lua/plugins"
-
-  SCRIPT_NVIM="${SCRIPT_DIR}/nvim"
-  SCRIPT_LUA="${SCRIPT_NVIM}/lua"
-  SCRIPT_PLUGINS="${SCRIPT_LUA}/plugins"
-
-  # Need to make sure the nvim config directory exists.
-  [[ ! -d "${HOME_NVIM}" ]] && mkdir -p "${HOME_NVIM}"
-
-  # Adding nvim directory files
-  symLink "${SCRIPT_NVIM}/README.md" "${HOME_NVIM}/README.md"
-  symLink "${SCRIPT_NVIM}/init.lua" "${HOME_NVIM}/init.lua"
-
-  # Setting the configs
-  symLinkDir "${SCRIPT_LUA}/config" "${HOME_NVIM}/lua/config"
-
-  # Setting the plugins
-  symLinkDir "${SCRIPT_PLUGINS}" "${HOME_PLUGINS}"
-fi
-
-# Claude-Code Configs
-if isInstalled claude; then
-  echo "Creating symLinks for Claude-Code.."
-  [[ -d "${HOME}/.claude" ]] && symLink "${SCRIPT_DIR}/claude/CLAUDE.md" ~/.claude/CLAUDE.md
-  echo "Done." && echo ""
-fi
-
-# Add personal scripts symlink
-[[ ! -d "${HOME}/scripts" ]] && mkdir "${HOME}/scripts"
-symLinkScripts() {
+symlink_scripts() {
+  local script_dir="${1}"
   echo "Creating symLinks for scripts.."
-  for script in "${SCRIPT_DIR}"/scripts/*; do
-    local scriptName="${script##*/}"
-    symLink "${script}" ~/scripts/"${scriptName}"
+
+  for script in "${script_dir}"/scripts/*; do
+    local script_name="${script##*/}"
+    create_symlink "${script}" "${HOME}/scripts/${script_name}"
     chmod +x "${script}"
   done
+
   echo "NOTE: Don't forget to add \`export PATH=\"\${HOME}/scripts:\${PATH}\"\` to your ~/.bashrc"
   echo "Done." && echo ""
 }
-symLinkScripts
 
-# TODO: Add other dotfile configs as needed
+main() {
+  local os_type
+  os_type="$(get_os_type)"
+
+  # Grabbing the script's directory
+  local script_path
+  script_path="$(realpath "${BASH_SOURCE[0]}")"
+  local script_dir
+  script_dir="$(dirname "${script_path}")"
+
+  # Shorthand function for checking if software is installed
+  chmod +x "${script_dir}/scripts/is-installed"
+  local is_installed
+  is_installed="${script_dir}/scripts/is-installed"
+
+  # i3 Configs
+  if "${is_installed}" i3; then
+    echo "Creating symLinks for i3.."
+    symlink_dir_files "${script_dir}/i3-wm" "${HOME}/.config/i3"
+  fi
+
+  # picom Configs
+  if "${is_installed}" picom; then
+    echo "Creating symLinks for picom.."
+    create_symlink "${script_dir}/picom/picom.conf" "${HOME}/.config/picom.conf"
+    echo "Done." && echo ""
+  fi
+
+  # Starship Configs
+  if "${is_installed}" starship; then
+    echo "Creating symLinks for starship.."
+    create_symlink "${script_dir}/starship/starship.toml" "${HOME}/.config/starship.toml"
+    echo "NOTE: Starship requires adding \`eval \"\$(starship init bash)\"\` to your ~/.bashrc file"
+    echo "Done." && echo ""
+  fi
+
+  # Tmux Configs
+  if "${is_installed}" tmux; then
+    echo "Creating symLinks for tmux.."
+    create_symlink "${script_dir}/tmux/tmux.conf" "${HOME}/.tmux.conf"
+    echo "Done." && echo ""
+  fi
+
+  # Alacritty Configs
+  if "${is_installed}" alacritty; then
+    echo "Creating symLinks for alacritty.."
+    [[ ! -d ~/.config/alacritty ]] && mkdir -p "${HOME}/.config/alacritty"
+    create_symlink "${script_dir}/alacritty/alacritty.toml" "${HOME}/.config/alacritty/alacritty.toml"
+    echo "Done." && echo ""
+  fi
+
+  # EDITOR to vim
+  if [[ "${EDITOR}" != "vim" ]]; then
+    echo "Checking for EDITOR set to 'vim'.."
+    echo "NOTE: Your current EDITOR is not set to vim."
+    echo "Consider adding \`export EDITOR=vim\` to your ~/.bashrc"
+    echo "Done." && echo ""
+  fi
+
+  # Vimrc Configs
+  if "${is_installed}" vim; then
+    echo "Creating symLinks for vimrc.."
+    create_symlink "${script_dir}/vimrc/${os_type}-vimrc" "${HOME}/.vimrc"
+    echo "Done." && echo ""
+  fi
+
+  # NeoVim Configs
+  if "${is_installed}" nvim; then
+    echo "Creating symLinks for nvim.."
+
+    create_symlink "${script_dir}/nvim" "${HOME}/.config/nvim"
+  fi
+
+  # Claude-Code Configs
+  if "${is_installed}" claude; then
+    echo "Creating symLinks for Claude-Code.."
+    [[ -d "${HOME}/.claude" ]] && create_symlink "${script_dir}/claude/CLAUDE.md" "${HOME}/.claude/CLAUDE.md"
+    echo "Done." && echo ""
+  fi
+
+  # Add personal scripts symlink
+  [[ ! -d "${HOME}/scripts" ]] && mkdir "${HOME}/scripts"
+  symlink_scripts "${script_dir}"
+}
+
+main "$@"
